[tool.poetry]
name = "dkg"
version = "0.1.0"
description = ""
authors = ["Uladzislau Hubar <hubar.uladzislau@gmail.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
pyyaml = "^6.0"
web3 = {version = "^6.0.0b9", allow-prereleases = true}
pandas = "^1.5.3"
eth-account = "^0.8.0"


[tool.poetry.group.dev.dependencies]
flake8 = "^6.0.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
